### ISSUE TITLE
Incorrectly work methods notifyItemRemovedAtPosition () and notifyItemInsertedAtPosition ()

### ISSUE THREAD

**Issue by UltraNeon** [zhukic/Sectioned-RecyclerView#18] opened 2018-06-12 19:58 UTC
When you add or delete data to a category, the positions in the adapter are shifted.
When you click on position 6, the adapter displays position 5. And so on.

**Comment by zhukic** [comment] 2018-06-13 16:07
H, @UltraNeon. Can you please provide more information about your problem?

**Comment by UltraNeon** [comment] 2018-06-13 16:40
Hello!
For example, I get the sorted data from Firestore in my application and display data using your Sectioned-RecyclerView library. Next, I interact with the data, add / delete / change. The problem consists in this: I have 3 categories in the recyclerView, call them A (contains 4 items), B (contains 3 items), C (contains 6 items), I add 3 more items to the category C and call the method notifyItemInsertedAtPosition ( int index); everything is perfectly inserted, but there is an incorrect recount of positions. Now if I click for example on position 4 in category C, then respond to position 5, or some other position from another category. The same is true with deletion, calling the method notifyItemRemovedAtPosition ()
Sorry for bad English)

**Comment by zhukic** [comment] 2018-06-13 16:57
Maybe this will help https://stackoverflow.com/questions/35812485/how-to-use-recyclerview-adapter-notifyiteminserted-removed-in-a-right-way

**Comment by UltraNeon** [comment] 2018-06-13 20:03
The item is deleted in this way

`int index = data.indexOf(item);
data.remove(index);
sectionedAdapter.notifyItemRemovedAtPosition(index);`

HashCode for the object is overrided correctly.
Tell me, please, why this approach works with the standard adapter, and the data is updated correctly, and with Sectioned-RecyclerView this is not so?

**Comment by UltraNeon** [comment] 2018-06-13 20:08
The item is deleted in this way

```
int index = data.indexOf(item); 
data.remove(index); 
sectionedAdapter.notifyItemRemovedAtPosition(index);
```

HashCode for the object is overrided correctly.
Tell me, please, why this approach works with the standard adapter, and the data is updated correctly, and with Sectioned-RecyclerView this is not so?

**Comment by UltraNeon** [comment] 2018-06-15 21:05
Здравствуйте, Владислав!
Я предположил, что вы знаете русский язык, изначально не посмотрел ваш профиль.
Моя проблема так и не решилась с вашим адаптером. Я так понял, что у вас и у других пользователей такой проблемы не возникало? Дело в том, что по какой то причине стандартные  методы `recyclerView` - `notifyItemInserted() ` и `notifyItemRemoved` которые вызываются в методах
`notifyItemRemovedAtPosition () и notifyItemInsertedAtPosition ()`, не правильно обновляют recyclerView. Все операции делаю правильно и с другими адаптерами такой проблемы не возникает. Очень понравился ваш адаптер, жаль конечно, что я скорее всего не решу эту проблему и придется пользоваться `notifyDataChange()`.

**Comment by zhukic** [comment] 2018-06-24 23:29
@UltraNeon Did you resolve your issue?

**Comment by UltraNeon** [comment] 2018-06-24 23:39
@zhukic 
Unfortunately no.
The fact is that for some reason the recyclerview itself does not want to update the position correctly. It's like some kind of bug, but why is it just me, I do not know. I tried many options with stackoverflow, searched the internet, parsed your code. As a result, the problem was removed only by the method notifyDataChanged

**Comment by GrenderG** [comment] 2018-07-24 17:11
I'm getting the same issue as @UltraNeon. After calling `notifyItemRemovedAtPosition()` method from your library positions get messed up. The only solution is to call `notifyDataSetChanged()`.

Seems like a bug in your method.

**Comment by zhukic** [comment] 2018-07-28 19:09
Hi, @GrenderG. It would be great if you create some sample project which demonstates this issue, because I can't reproduce it. Thanks.

**Comment by UltraNeon** [comment] 2018-07-29 00:36
https://github.com/UltraNeon/Test

I posted a test project. Click to remove the apple, and then press the Cambala

**Comment by zhukic** [comment] 2018-07-29 11:35
@UltraNeon thank you for your time you've spent to create this test project.

The problem is when you try to remove Cambala after Apple `itemPosition` for Cambala is still 1, but it actual position is 0 since you just removed the Apple. That's happenning because ViewHolder for Cambala is not updated after `notifyItemRemovedAtPosition`.
The solution is:
```java
@Override
    public void onBindItemViewHolder(final ItemViewHolder holder, final int itemPosition) {
        final Item item = list.get(itemPosition);

        holder.item.setText(item.getName());

        holder.frameLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(activity, String.valueOf(itemPosition), Toast.LENGTH_SHORT);
            }
        });

        holder.remove.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                removeItem(item);
            }
        });
    }

    private void removeItem(Item item) {
        final int itemIndex = list.indexOf(item);
        list.remove(itemIndex);
        notifyItemRemovedAtPosition(itemIndex);
    }
```
@UltraNeon, @GrenderG please the try out [the sample project](https://github.com/zhukic/Sectioned-RecyclerView/tree/master/sample) where you are able to remove items from list.
@UltraNeon if you have any question - please ask, otherwise - close issue. 
Thanks.

**Comment by UltraNeon** [comment] 2018-07-29 12:01
Well, your example works!
But what if I get a callback from the database, db return the item that was deleted?
How to update adapter?

Database listener method
`if (documentChange.getType() == DocumentChange.Type.REMOVED) {

                   Item item = documentChange.getDocument().toObject(Item.class);

                    if (sectionedAdapter != null) {
                        sectionedAdapter.removeItem(productItem);
`
`public void removeItem(final Item item) {
        int position = listItems.indexOf(item);
        listItems.remove(position);
        notifyItemRemovedAtPosition(position);

    }`

**Comment by zhukic** [comment] 2018-07-29 13:37
@UltraNeon you need to obtain the list position of your removed item and then call `notifyItemRemovedAtPosition(itemPosition)`

**Comment by zhukic** [comment] 2018-08-04 13:00
@UltraNeon, @GrenderG can I close this issue?

**Comment by UltraNeon** [comment] 2018-08-04 13:04
@zhukic 
Of course
You helped with the solution of the problem, there are no more questions.
Thank you so much!

**Comment by GrenderG** [comment] 2018-08-05 23:05
Yes, thanks! :stuck_out_tongue:

**Closed** 2018-08-06 06:10 UTC
